version: 5.1.0
variant: default
logo: /images/logo.png
head:
  favicon: /images/favicon.ico
  manifest:
    name:
    short_name:
    start_url:
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss: /atom.xml
navbar:
  menu:
    Home: /
    Categories: /categories
    Tags: /tags
    About: /about
footer:
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  readtime: true
  update_time: false
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - position: left
    type: profile
    author: Raighne.Weng
    author_title: Coder
    location: Nanking/Chengdu/Singapore
    avatar: /images/avatar.png
    avatar_rounded: true
    gravatar:
    follow_link: https://github.com/raighneweng
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/raighneweng
      RSS:
        icon: fas fa-rss
        url: /atom.xml
  - position: left
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: left
    type: recent_posts
  - position: left
    type: tags
  - position: left
    type: subscribe_email
    description:
    feedburner_id: RaighnesBlog
  # - position: left
  #   type: adsense
  #   client_id: ca-pub-2410395661948138
  #   slot_id: 1274867073
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id:
  bing_webmaster:
    tracking_id:
  busuanzi: false
  cnzz:
    id:
    web_id:
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id:
  hotjar:
    site_id:
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
