# Site
title: Raighne's Blog
subtitle:
description: I‘m looking for freedom
author: Raighne.Weng
author_title: "ECE Student"
avatar: css/images/avatar.png
location: "Nanking, China"
follow: https://github.com/raighneweng/
language: zh-CN
timezone: Asia/Shanghai
since: 2014.12.26 # The start year showing in your copyright section.

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://raighne.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [README.md]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus

# Disqus
# disqus_shortname: raighnewengblog

# DuoShuo
#duoshuo_shortname: raighnewengblog

# plugins:
# - hexo-generator-feed
# - hexo-generator-sitemap
# - hexo-generator-baidu-sitemap

#sitemap
#baidusitemap:
#    path:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gh_token@github.com/raighneweng/raighneweng.github.io.git
  branch: master
