baseURL = '/'
languageCode = 'en-us'
title = "Raighne's Blog"
theme = "paper"

[taxonomies]
   tag = "tags"

[params]
  # color style
  color = 'linen'                          

  # header social icons
  github = 'raighneweng'                 
  mastodon = 'https://mastodon.social/@raighne'         
  rss = true                                